first commit
VladislavLisovenko/task-management pull request #1
Opened 2024-02-09 07:47 UTC by VladislavLisovenko

2024-02-10 07:19 UTC, vladislavmass requested changes

2024-02-10 07:19 UTC, vladislavmass commented on server/handlers/tasks.go
> +	tlf := decodeEntity[entities.TaskListFilter](w, r)
У Get запросов по RFC не может быть тела. Все параметры  Get запросе передаются в его теле

2024-02-10 07:19 UTC, vladislavmass commented on server/db/users.go
> +		return AddUser(userName)
Делать добавление пользователя в виде сайд эффекта не самая хорошая идея. Лучше всегда ориентироваться на прямые действие пользователя.

2024-02-10 07:19 UTC, vladislavmass commented on server/entities/tasklistfilter.go
> +	ExpirationDateFrom time.Time
Нет валидации на то, что старт периода раньше его конца. Например я могу запросить период с 12.01.2024 по 11.02.1987

2024-02-10 07:19 UTC, vladislavmass commented on server/entities/tasks.go
> +	ExpirationDate time.Time `json:"expirationDate"`
Было бы отлично хранить еще и дату создания задания

2024-02-10 07:19 UTC, vladislavmass commented on server/entities/tasks.go
> +	ExpirationDate time.Time `json:"expirationDate"`
А также нужна валидация на то, что дата окончания не меньше даты создания

2024-02-12 08:25 UTC, VladislavLisovenko commented on server/handlers/tasks.go
> +	tlf := decodeEntity[entities.TaskListFilter](w, r)
поправил

2024-02-12 08:26 UTC, VladislavLisovenko commented on server/db/users.go
> +		return AddUser(userName)
добавил меню для создания/ввода имени пользователя

2024-02-12 15:13 UTC, VladislavLisovenko commented on server/entities/tasklistfilter.go
> +	ExpirationDateFrom time.Time
добавил

2024-02-12 15:27 UTC, VladislavLisovenko commented on server/entities/tasks.go
> +	ExpirationDate time.Time `json:"expirationDate"`
добавил дату создания и валидацию на сервере

2024-02-13 17:32 UTC, vladislavmass requested changes

2024-02-13 17:32 UTC, vladislavmass commented on server/handlers/users.go
> +		w.Header().Add("error", "Имя пользователя не указано")
Ошибки принято возвращать не хедарах а лучше вернуть json в котором будет поля error и в нем уже текст ошибки

2024-02-13 17:32 UTC, vladislavmass commented on server/handlers/users.go
> +		w.WriteHeader(http.StatusNotFound)
В данном случае больше подойдет статус BadRequest.

2024-02-13 17:32 UTC, vladislavmass commented on server/handlers/users.go
> +	w.Header().Add("id", strconv.Itoa(user.GetID()))
Возвращать ответ нужно  в теле  запроса, желательно в формате json. И желательно вернуть всю структуру User

2024-02-13 17:32 UTC, vladislavmass commented on server/handlers/general.go
> +func decodeEntity[T Entity](w http.ResponseWriter, r *http.Request) T {
Лучше было бы если бы этот метод принимал в себя массив байт и возвращал указатель на  структуру T и ошибку. При таком раскладе метод бы отвечал своему названию и был бы соблюден принцип единой ответственности. А также Body после чтения из него надо закрывать

2024-02-13 17:32 UTC, vladislavmass commented on server/handlers/users.go
> +	user, err := db.AddUser(userDecoded.Name)
Подумайте что тут будет если я передам пустое имя и как это обработать. Это вопрос относительно валидации

2024-02-13 17:32 UTC, vladislavmass commented on docker-entrypoint-initdb.d/filldb.sql
> +    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
Почему решили сделать первичным ключом id а не name. Ведь по сути текущая реализация не способна работать с несколькими пользователями у которых 1 и тоже имя.

2024-02-13 17:32 UTC, vladislavmass commented on server/handlers/users.go
> +		w.WriteHeader(http.StatusBadRequest)
Если пользователь не создался, а оишбку что имя уже занято база вернуть не может то тут больше подойдет либо 500 ошибка либо 503

2024-02-13 17:32 UTC, vladislavmass commented on server/handlers/tasks.go
> +	task := decodeEntity[entities.Task](w, r)
Хорошо бы иметь защиту от ситауции когда ряд полей пустые.

2024-02-13 17:32 UTC, vladislavmass commented on server/handlers/tasks.go
> +	if task.CreationDate.After(task.ExpirationDate) {
Дата создания обычно берется на сервере а не запрашивается у пользователя. Так как дата создания это всегда текущий момент

2024-02-14 13:57 UTC, merged